language: go

sudo: true

go:
  - "1.10"

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverprofile.txt
